extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
extern Lights1 bob_dl_f3d_material_lights;
extern Lights1 bob_dl_protrustionwalls_lights;
extern Lights1 bob_dl_Ground_001_lights;
extern Lights1 bob_dl_groundsides_lights;
extern Lights0 bob_dl_protrusion_lights;
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_0[106];
extern Gfx bob_dl_Plane_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_1[263];
extern Gfx bob_dl_Plane_mesh_layer_1_tri_1[];
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_2[128];
extern Gfx bob_dl_Plane_mesh_layer_1_tri_2[];
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_3[48];
extern Gfx bob_dl_Plane_mesh_layer_1_tri_3[];
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_4[334];
extern Gfx bob_dl_Plane_mesh_layer_1_tri_4[];
extern Gfx mat_bob_dl_f3d_material[];
extern Gfx mat_bob_dl_protrustionwalls[];
extern Gfx mat_revert_bob_dl_protrustionwalls[];
extern Gfx mat_bob_dl_Ground_001[];
extern Gfx mat_revert_bob_dl_Ground_001[];
extern Gfx mat_bob_dl_groundsides[];
extern Gfx mat_revert_bob_dl_groundsides[];
extern Gfx mat_bob_dl_protrusion[];
extern Gfx bob_dl_Plane_mesh_layer_1[];
extern Gfx bob_dl_material_revert_render_settings[];
